### ISSUE TITLE
How to use this addon?

### ISSUE THREAD

**Issue by dmsurti** [felixSchl/bake-rigify#1]
@felixSchl Thanks for this add-on. I forked/cloned this repo and from User Preferences in Blender, installed this add on. Then in one of my blend files which has a character with rigify rig, I checked in N Panel, Object Tab and Data tab, but cannot see the Bake button as can be seen here: http://blenderaddonlist.blogspot.in/2014/05/addon-bake-rigify-rig.html.

Any install steps will be helpful. Thanks.

**Comment by felixSchl** [comment]
Could you check if the plugin is loaded? If you bring up a console and type `bpy.ops.object.bak<C-SPACE>`, does it auto-complete to `bake_rigify`?

Other than that, the panel is shown/hidden based on a simple poll method, which you can look up [here](https://github.com/felixSchl/bake-rigify/blob/master/__init__.py#L13).

**Comment by dmsurti** [comment]
In the console, I get only: 
`bake(`
`bake_image(`
for bpy.ops.object.bake.

I am using Blender Version 2.71 on Mac OS X 10.10 Yosemite.

**Comment by felixSchl** [comment]
I cannot reproduce this with Blender version 2.74. I am also on OS X version 10.10.

Here are the steps I took:
1. I clone the repo to into, e.g. `[...]/blender.app/Contents/Resources/2.74/scripts/addons/bake-rigify`.
2. In addon manager, enable the `bake rigify` addon.
3. Select an armature in object mode
4. In the properties panel, under the armature data tab, expand "Rigify Bake" and hit the button there.

If you cannot even see the operator in the console, it means something went wrong when the addon
was loaded... Could you launch blender from the terminal and report any suspicious output?

**Comment by dmsurti** [comment]
I was trying to install the script via `Install From File` under User Preferences -> Addons. That did not install the script it seems and is the wrong way to install an add on (I am blender novice!).

Following your steps, I could succesfully install the add-on (by cloning the repo) and could also bake the animation. 

Thanks for your help in getting this resolved and this is a very useful add-on as I could now transfer animations from Rigify to Mixamo rigged characters. Closing this issue.

**Comment by felixSchl** [comment]
The reason that it would not work, I suppose is that the file is called `__init__.py`, meaning to say it needs it's housing folder to be an actual module. Not sure what the `Install From File` operator does, though, so I might be wrong.

That aside, you can still install this addon from file, just download the zipped up script from the [release page](https://github.com/felixSchl/bake-rigify/releases) and select the zip file in the `Install From File` dialog.
